apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: "TCP"
      port: 8090
      targetPort: 8090
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  selector:
    matchLabels:
      app: flask-app
  replicas: 1
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-test-app
          image: docker.io/abdullahajaz/classtask_02
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8090
